use bonus_track;

SELECT CONCAT(TITULO, " - ", ARTISTA) AS CANCION, GENERO  FROM TOP_SPOTIFY ORDER BY CANCION;
SELECT CONCAT_WS(" - ",TITULO, ARTISTA) AS CANCION, GENERO  FROM TOP_SPOTIFY ORDER BY CANCION;
SELECT CONCAT_WS(" - ",TITULO, ARTISTA) AS CANCION, UPPER(GENERO)  FROM TOP_SPOTIFY ORDER BY CANCION;
SELECT COUNT(*) AS CANCIONES FROM TOP_SPOTIFY;
SELECT ANO, COUNT(*) AS CANCIONES FROM TOP_SPOTIFY GROUP BY ANO;
SELECT ANO, COUNT(*) AS CANCIONES FROM TOP_SPOTIFY GROUP BY ANO HAVING CANCIONES >= 50;

DESC TOP_SPOTIFY;