USE LIBRERIA;

SELECT CONCAT(APELLIDO, ", ", NOMBRE) AS AUTOR, PROVINCIA FROM AUTORES ORDER BY APELLIDO;
SELECT CONCAT_WS(", ",APELLIDO, NOMBRE) AS AUTOR, PROVINCIA FROM AUTORES ORDER BY APELLIDO;
SELECT UPPER(CONCAT_WS(", ",APELLIDO, NOMBRE)) AS AUTOR, PROVINCIA FROM AUTORES ORDER BY APELLIDO;


SELECT CONCAT(APELLIDO, ", ", NOMBRE) AS EMPLEADO, YEAR(FECHA_INGRESO) AS INGRESO FROM EMPLEADOS ORDER BY INGRESO DESC;

DESC EMPLEADOS;