use libreria;

SELECT CONCAT(APELLIDO, ", ", NOMBRE) AS EMPLEADO, YEAR(FECHA_INGRESO) AS INGRESO, TIMESTAMPDIFF(YEAR, FECHA_INGRESO, CURDATE()) AS ANTIGÜEDAD FROM EMPLEADOS ORDER BY INGRESO DESC;

SELECT MIN(PRECIO) AS "MENOR PRECIO" FROM LIBROS;
SELECT MIN(PRECIO) AS "MENOR PRECIO", MAX(PRECIO) AS "MAYOR PRECIO" FROM LIBROS;
SELECT MIN(PRECIO) AS "MENOR PRECIO", MAX(PRECIO) AS "MAYOR PRECIO", ROUND(AVG(PRECIO), 2) AS "PRECIO PROMEDIO" FROM LIBROS;
SELECT CATEGORÍA, MIN(PRECIO) AS "MENOR PRECIO", MAX(PRECIO) AS "MAYOR PRECIO", ROUND(AVG(PRECIO), 2) AS "PRECIO PROMEDIO" FROM LIBROS GROUP BY CATEGORÍA;
SELECT CATEGORÍA, MIN(PRECIO) AS "MENOR PRECIO", MAX(PRECIO) AS "MAYOR PRECIO", ROUND(AVG(PRECIO), 2) AS "PRECIO PROMEDIO" FROM LIBROS GROUP BY CATEGORÍA HAVING CATEGORÍA <> "SIN ASIGNAR";

DESC LIBROS;