USE LABORATORIO;
#1
CREATE TABLE VARONES SELECT * FROM NACIMIENTOS WHERE SEXO = "MASCULINO";
SELECT COUNT(*) FROM VARONES;  #98397
#2
CREATE TABLE MUJERES SELECT * FROM NACIMIENTOS WHERE SEXO = "FEMENINO";
SELECT COUNT(*) FROM MUJERES;  #94763
#3
CREATE TABLE INDETERMINADOS SELECT * FROM NACIMIENTOS WHERE SEXO = "INDETERMINADO";
SELECT COUNT(*) FROM INDETERMINADOS;  #24
#4
DROP TABLE NACIMIENTOS;

