USE LABORATORIO;
#1
SET SQL_SAFE_UPDATES = 0;
UPDATE CLIENTES_NEPTUNO SET PAIS = "USA" WHERE PAIS = "ESTADOS UNIDOS";
SELECT * FROM CLIENTES_NEPTUNO;
#2
UPDATE CLIENTES_NEPTUNO SET NOMBRECOMPANIA = upper(NOMBRECOMPANIA);
SELECT * FROM CLIENTES_NEPTUNO;
#3
UPDATE CLIENTES_NEPTUNO SET CIUDAD = upper(CIUDAD), PAIS = upper(PAIS);
SELECT * FROM CLIENTES_NEPTUNO;
#4
ALTER TABLE EMPLEADOS ADD COLUMN NOMBRE_EMPLEADO varchar(30) AFTER IDEMPLEADO; 
UPDATE EMPLEADOS SET NOMBRE_EMPLEADO = CONCAT(APELLIDOS, ', ', NOMBRE);
ALTER TABLE EMPLEADOS DROP COLUMN APELLIDOS, DROP COLUMN NOMBRE;
SELECT * FROM EMPLEADOS;
#5
ALTER TABLE CLIENTES ADD COLUMN TIPO varchar(3) AFTER RESPONSABLE;
UPDATE CLIENTES SET TIPO = "VIP" WHERE CIUDAD  = "MADRID";
SELECT * FROM CLIENTES;
#6
ALTER TABLE CLIENTES MODIFY TELEFONO varchar(20);
UPDATE CLIENTES SET TELEFONO = CONCAT("+34-", TELEFONO) WHERE TELEFONO IS NOT NULL;
SELECT * FROM CLIENTES;
#7
ALTER TABLE PRODUCTOS ADD COLUMN FECHA date;
UPDATE PRODUCTOS SET FECHA = CONCAT(ANO,'-', MES,'-', DIA);
ALTER TABLE PRODUCTOS DROP ANO,DROP MES,DROP DIA;
UPDATE PRODUCTOS SET ORIGEN = "ESPAÑA" WHERE ORIGEN = "ESPANA";
SELECT * FROM PRODUCTOS;
#8
ALTER TABLE PRODUCTOS_NEPTUNO MODIFY SUSPENDIDO VARCHAR(2);
UPDATE PRODUCTOS_NEPTUNO SET SUSPENDIDO = "NO" WHERE SUSPENDIDO = "0";
UPDATE PRODUCTOS_NEPTUNO SET SUSPENDIDO = "SI" WHERE SUSPENDIDO = 1;
SELECT * FROM PRODUCTOS_NEPTUNO;
#9
UPDATE PRODUCTOS_NEPTUNO SET PRECIOUNIDAD = ROUND(PRECIOUNIDAD * 1.10, 2);
#10
UPDATE PROVEEDORES SET REGION = "NULL" WHERE REGION = "";
SELECT * FROM PROVEEDORES;
#11
UPDATE CLIENTES SET CIUDAD = CONCAT(UPPER(LEFT(CIUDAD, 1)), LOWER(SUBSTRING(CIUDAD, 2,LENGTH(CIUDAD))));
SELECT * FROM CLIENTES;
#12
CREATE TABLE PRODUCTOS_SUSPENDIDOS SELECT * FROM PRODUCTOS_NEPTUNO WHERE SUSPENDIDO = "SI";
SELECT * FROM PRODUCTOS_SUSPENDIDOS;
SELECT COUNT(*) FROM PRODUCTOS_SUSPENDIDOS;
