#1
UPDATE PRODUCTOS_NEPTUNO SET SUSPENDIDO = "SI" WHERE IDPROVEEDOR = "1";
SELECT * FROM PRODUCTOS_NEPTUNO;
#2
INSERT INTO PRODUCTOS_SUSPENDIDOS(IDPRODUCTO, NOMBREPRODUCTO, NOMBRECONTACTO,
 NOMBRECATEGORIA, PRECIOUNIDAD, SUSPENDIDO, IDPROVEEDOR) SELECT IDPRODUCTO, 
 NOMBREPRODUCTO, NOMBRECONTACTO, NOMBRECATEGORIA, PRECIOUNIDAD, SUSPENDIDO, 
 IDPROVEEDOR FROM PRODUCTOS_NEPTUNO WHERE SUSPENDIDO = "SI";
 #1-eliminacion
DELETE FROM PRODUCTOS_NEPTUNO WHERE SUSPENDIDO = 'SI';
