USE BONUS_TRACK;
#EJERCICIO 1
#1
SELECT ARTISTA, TITULO FROM ÚLTIMOS_LANZAMIENTOS WHERE ANO = (SELECT MAX(ANO) FROM ÚLTIMOS_LANZAMIENTOS)
ORDER BY ARTISTA, TITULO;
#2
SELECT TITULO FROM TOP_SPOTIFY WHERE ARTISTA = "LADY GAGA" AND PERMANENCIA =
(SELECT MAX(PERMANENCIA) FROM TOP_SPOTIFY) ORDER BY TITULO;
#3
SELECT ARTISTA, TITULO, CASE WHEN GENERO LIKE "%POP%" THEN "POP"
WHEN GENERO LIKE "%ELECTRO%" OR "%HOUSE%" THEN "ELECTRÓNICA"
ELSE "OTRO" END AS TIPO
FROM TOP_SPOTIFY ORDER BY ARTISTA, TITULO;