#EJERCICIO 3
USE LIBRERIA;
#1
SELECT * FROM LIBROS WHERE PRECIO > (SELECT AVG(PRECIO) FROM LIBROS) ORDER BY TÍTULO;
#2
SELECT * FROM LIBROS WHERE CATEGORÍA = "NOVELAS" AND 
PRECIO > (SELECT MAX(PRECIO) FROM LIBROS WHERE CATEGORÍA = "ENSAYOS") ORDER BY PRECIO DESC;
#3
SELECT * FROM EMPLEADOS WHERE PERMANENCIA = (SELECT MAX(PERMANENCIA) FROM EMPLEADOS);
#4
SELECT * FROM EMPLEADOS WHERE PUESTO_ID = (SELECT MAX(PUESTO_ID) FROM EMPLEADOS);
#5
SELECT LIBRO_ID, TÍTULO, CATEGORÍA, PRECIO_PUBLICO, CASE WHEN PRECIO < 15 THEN 'ECONÓMICO'
WHEN PRECIO BETWEEN 15 AND 30 THEN 'REGULAR'
ELSE 'DELUXE' END AS TIPO FROM LIBROS WHERE PRECIO IS NOT NULL ORDER BY TÍTULO;
#6
SELECT CONCAT(APELLIDO, ', ', NOMBRE) AS EMPLEADO FROM EMPLEADOS WHERE PUESTO_ID = 9
UNION
SELECT CONCAT(APELLIDO, ', ', NOMBRE) FROM EMPLEADOS_ANTERIORES WHERE PUESTO_ID = 9
ORDER BY EMPLEADO;
#7
SELECT L.LIBRO_ID, L.TÍTULO, L.PRECIO_PUBLICO, V.LOCAL_ID, V.FACTURA_NRO, V.CANTIDAD FROM LIBROS L 
JOIN VENTAS V ORDER BY L.TÍTULO;
#8
SELECT L.LIBRO_ID, L.TÍTULO, L.PRECIO_PUBLICO, V.LOCAL_ID, V.FACTURA_NRO, V.CANTIDAD, 
ROUND((L.PRECIO_PUBLICO * V.CANTIDAD), 2) AS TOTAL FROM LIBROS L 
JOIN VENTAS V ORDER BY L.TÍTULO;
#9
SELECT L.TÍTULO FROM LIBROS L LEFT JOIN VENTAS V ON L.LIBRO_ID = V.LIBRO_ID
WHERE FACTURA_NRO IS NULL ORDER BY TÍTULO;
