#1 
USE BONUS_TRACK;

SELECT * FROM TOP_SPOTIFY;
SELECT TITULO, ARTISTA, GENERO FROM TOP_SPOTIFY;
SELECT TITULO, ARTISTA, GENERO FROM TOP_SPOTIFY ORDER BY GENERO;
SELECT TITULO, ARTISTA, GENERO FROM TOP_SPOTIFY ORDER BY GENERO, ARTISTA;

#2
SELECT TITULO, ARTISTA, GENERO FROM TOP_SPOTIFY ORDER BY ARTISTA, TITULO;
SELECT TITULO, ARTISTA, GENERO FROM TOP_SPOTIFY ORDER BY ARTISTA, TITULO LIMIT 10;

SELECT * FROM TOP_SPOTIFY WHERE ARTISTA = 'MADONNA';
SELECT * FROM TOP_SPOTIFY WHERE GENERO = 'POP' ORDER BY TITULO;
SELECT * FROM TOP_SPOTIFY WHERE GENERO = 'POP' AND ANO = 2015 ORDER BY ARTISTA, TITULO;
SELECT * FROM TOP_SPOTIFY WHERE ANO < 2011 AND GENERO = 'DANCE POP' ORDER BY TITULO;

#3