USE BONUS_TRACK;

#EJERCICIO 1 
#1.1
UPDATE TOP_SPOTIFY SET TITULO = UPPER(TITULO), ARTISTA  = UPPER(ARTISTA);
#1.2
ALTER TABLE TOP_SPOTIFY ADD COLUMN PERMANENCIA INT;
UPDATE TOP_SPOTIFY SET PERMANENCIA = YEAR(CURDATE()) - ANO;
#1.3
CREATE TABLE ÚLTIMOS_LANZAMIENTOS SELECT * FROM TOP_SPOTIFY WHERE PERMANENCIA <= 3;
DELETE FROM TOP_SPOTIFY WHERE PERMANENCIA <=3;
#1.4
INSERT INTO TOP_SPOTIFY(ID, TITULO, ARTISTA, GENERO, ANO, PERMANENCIA) VALUES(610, "GOD CONTROL", "MADONNA", "POP", 2018, 3);
#1.5
INSERT INTO ÚLTIMOS_LANZAMIENTOS SELECT * FROM TOP_SPOTIFY  WHERE PERMANENCIA <= 3;
DELETE FROM TOP_SPOTIFY WHERE PERMANENCIA <=3;

#EJERCICIO 2
USE LIBRERIA;
#2.1
UPDATE AUTORES SET NOMBRE = "Esteban" WHERE APELLIDO = "ECHEVERRÍA";
#2.2
ALTER TABLE EMPLEADOS ADD COLUMN PERMANENCIA INT;
UPDATE EMPLEADOS SET PERMANENCIA = YEAR(CURDATE()) - YEAR(FECHA_INGRESO);
#2.3
ALTER TABLE LIBROS ADD COLUMN PRECIO_PUBLICO float;
UPDATE LIBROS SET PRECIO_PUBLICO = ROUND(PRECIO*1.21, 2);
SELECT * FROM LIBROS; 