#EJERCICIO 2
USE LIBRERIA;
#2.1
UPDATE AUTORES SET NOMBRE = "Esteban" WHERE APELLIDO = "ECHEVERRÍA";
#2.2
ALTER TABLE EMPLEADOS ADD COLUMN PERMANENCIA INT;
UPDATE EMPLEADOS SET PERMANENCIA = YEAR(CURDATE()) - YEAR(FECHA_INGRESO);
#2.3
ALTER TABLE LIBROS ADD COLUMN PRECIO_PUBLICO float;
UPDATE LIBROS SET PRECIO_PUBLICO = ROUND(PRECIO*1.21, 2);
SELECT * FROM LIBROS; 