#EJERCICIO 3
#3.1
CREATE TABLE EMPLEADOS_ANTERIORES SELECT * FROM EMPLEADOS 
WHERE APELLIDO = "THOMAS" OR APELLIDO = "PEREIRA" OR APELLIDO = "DEVO";
DELETE FROM EMPLEADOS WHERE APELLIDO = "THOMAS" OR APELLIDO = "PEREIRA" OR APELLIDO = "DEVO";
#3.2
INSERT INTO EMPLEADOS_ANTERIORES SELECT * FROM EMPLEADOS WHERE APELLIDO = "CRUZ";
DELETE FROM EMPLEADOS WHERE APELLIDO = "CRUZ";