USE LABORATORIO;

CREATE TABLE EQUIPOS(EQUIPO VARCHAR(20) PRIMARY KEY);
INSERT INTO EQUIPOS VALUES ("ARGENTINA"), ("BRASIL"), ("PARAGUAY"), ("CHILE"), ("URUGUAY"),
("COLOMBIA"), ("ECUADOR"), ("PERÚ"), ("BOLIVIA"), 
("VENEZUELA");
SELECT IDPRODUCTO, NOMBREPRODUCTO, NOMBRE_EMPLEADO FROM PRODUCTOS_NEPTUNO, EMPLEADOS
 WHERE PRODUCTOS_NEPTUNO.IDPRODUCTO = EMPLEADOS.IDEMPLEADO;