#1
SELECT * FROM VARONES WHERE SEMANAS < 20
UNION
SELECT * FROM MUJERES WHERE SEMANAS < 20
UNION
SELECT * FROM INDETERMINADOS WHERE SEMANAS < 20;
#2
SELECT * FROM VARONES WHERE MONTH(FECHA) = 09 AND SEMANAS > 40 AND NACIONALIDAD = 'CHILENA' AND ESTADO_CIVIL_MADRE = 'CASADA'
UNION
SELECT * FROM MUJERES WHERE MONTH(FECHA) = 09 AND SEMANAS > 40 AND NACIONALIDAD = 'CHILENA' AND ESTADO_CIVIL_MADRE = 'CASADA'
UNION
SELECT * FROM INDETERMINADOS WHERE MONTH(FECHA) = 09 AND SEMANAS > 40 AND NACIONALIDAD = 'CHILENA' AND ESTADO_CIVIL_MADRE = 'CASADA';
#3
SELECT * FROM PRODUCTOS_NEPTUNO WHERE PRECIOUNIDAD > 80
UNION
SELECT * FROM PRODUCTOS_SUSPENDIDOS WHERE PRECIOUNIDAD > 80
ORDER BY NOMBREPRODUCTO;
#4
SELECT *, 'A LA VENTA' AS CONDICION FROM PRODUCTOS_NEPTUNO WHERE PRECIOUNIDAD > 80
UNION
SELECT *, 'SUSPENDIDO' AS CONDICION FROM PRODUCTOS_SUSPENDIDOS WHERE PRECIOUNIDAD > 80
ORDER BY NOMBREPRODUCTO;
#5 / 7
SELECT * FROM PRODUCTOS_NEPTUNO WHERE NOMBRECATEGORIA = "BEBIDAS"
UNION
SELECT * FROM PRODUCTOS_SUSPENDIDOS WHERE NOMBRECATEGORIA = "BEBIDAS"
ORDER BY NOMBREPRODUCTO;
#6
INSERT INTO PRODUCTOS_SUSPENDIDOS(IDPRODUCTO, NOMBREPRODUCTO, NOMBRECONTACTO, NOMBRECATEGORIA,
 PRECIOUNIDAD, SUSPENDIDO, IDPROVEEDOR) 
SELECT IDPRODUCTO, NOMBREPRODUCTO, NOMBRECONTACTO, NOMBRECATEGORIA, 
PRECIOUNIDAD, SUSPENDIDO, IDPROVEEDOR FROM PRODUCTOS_NEPTUNO WHERE IDPRODUCTO = 43;
#8
SELECT * FROM PRODUCTOS_NEPTUNO WHERE NOMBRECATEGORIA = "BEBIDAS"
UNION ALL
SELECT * FROM PRODUCTOS_SUSPENDIDOS WHERE NOMBRECATEGORIA = "BEBIDAS"
ORDER BY NOMBREPRODUCTO;
#9
SET SQL_SAFE_UPDATES = 0;
DELETE FROM PRODUCTOS_SUSPENDIDOS WHERE IDPRODUCTO = 43;