USE LABORATORIO;
#1
SELECT * FROM PRODUCTOS_NEPTUNO WHERE PRECIOUNIDAD > (SELECT AVG(PRECIOUNIDAD) FROM PRODUCTOS_NEPTUNO) ORDER BY NOMBREPRODUCTO;
#2
SELECT * FROM PRODUCTOS_NEPTUNO WHERE PRECIOUNIDAD > (SELECT MAX(PRECIOUNIDAD) FROM PRODUCTOS_SUSPENDIDOS) ORDER BY PRECIOUNIDAD DESC;
#3
SELECT * FROM VARONES WHERE SEMANAS < (SELECT MIN(SEMANAS) FROM INDETERMINADOS);
#4
SELECT * FROM PRODUCTOS_NEPTUNO WHERE LEFT(NOMBREPRODUCTO, 1) = (SELECT LEFT(NOMBRE_EMPLEADO, 1) FROM EMPLEADOS WHERE IDEMPLEADO = 8) ORDER BY NOMBREPRODUCTO;
#5
SELECT * FROM PRODUCTOS_NEPTUNO WHERE IDPROVEEDOR = (SELECT MAX(IDPROVEEDOR) FROM PRODUCTOS_NEPTUNO) ORDER BY NOMBREPRODUCTO;
#6
SELECT * FROM PRODUCTOS_NEPTUNO WHERE NOMBRECATEGORIA = "BEBIDAS" AND PRECIOUNIDAD > (SELECT MAX(PRECIOUNIDAD) AND NOMBRECATEGORIA = "CONDIMENTOS");
#7
SELECT * FROM MUJERES WHERE EDAD_MADRE > (SELECT MAX(EDAD_MADRE) FROM VARONES);
#8
SELECT NOMBRECOMPANIA, CIUDAD, PAIS FROM CLIENTES_NEPTUNO WHERE NOMBRECOMPANIA IN (SELECT NOMBRECOMPANIA FROM PEDIDOS_NEPTUNO WHERE CARGO > 500) ORDER BY NOMBRECOMPANIA;
