#1
SELECT IDCLIENTE, NOMBRECOMPANIA, CIUDAD, PAIS,
CASE WHEN PAIS = 'MÉXICO' OR PAIS = 'CANADÁ' OR PAIS = 'USA' THEN 'AMÉRICA DEL NORTE'
WHEN PAIS = 'ARGENTINA' OR PAIS = 'VENEZUELA' OR PAIS = 'BRASIL' THEN 'AMÉRICA DEL SUR'
ELSE 'EUROPA' END AS CONTINENTE  FROM CLIENTES_NEPTUNO ORDER BY CONTINENTE, PAIS; 

 #2
 SELECT IDPEDIDO, NOMBRECOMPANIA, FECHAPEDIDO, CARGO,
 CASE WHEN CARGO > 700 THEN 'EXCELENTE'
 WHEN CARGO BETWEEN 500 AND 700 THEN 'MUY BUENO'
 WHEN CARGO BETWEEN 250 AND 500 THEN 'BUENO'
 WHEN CARGO BETWEEN 50 AND 250 THEN 'REGULAR'
 ELSE 'MALO' END
 AS EVALUACION  FROM PEDIDOS_NEPTUNO ORDER BY CARGO DESC;
 
 #3
 SELECT IDPRODUCTO, NOMBREPRODUCTO, NOMBRECATEGORIA, PRECIOUNIDAD, 
 CASE WHEN PRECIOUNIDAD > 100 THEN 'DELUXE'
 WHEN PRECIOUNIDAD BETWEEN 10 AND 100 THEN 'REGULAR'
 ELSE 'ECONÓMICO' END
 AS TIPO FROM PRODUCTOS_NEPTUNO ORDER BY PRECIOUNIDAD DESC;
 
